apiVersion: v1
kind: Service
metadata:
  name: bss-cpct-eslog
  labels:
    name: bss-cpct-eslog
spec:
  type: NodePort
  ports:
  - port: 30808
    nodePort: 30808
  selector:
    name: bss-cpct-eslog
