#端口配置
server:
  port: 8088

#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://116.62.129.215:3306/fpc_system?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: yannis
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
