#端口配置
server:
  port: 8080

#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://47.94.168.117:3306/fpc_system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: Yanlei2018
    driver-class-name: com.mysql.jdbc.Driver
