#端口配置
server:
  port: 30321

spring:
# 第一数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.252.170:30304/cpct_system?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: xc.cpct

# 第二数据源
  datasourceprd:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.253.29:8801/smt_bss_cpc_cpct?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_cpct_user
    password: cpc_cpct_user_123

# 第三数据源
  datasourcethird:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.252.170:30304/SMT_BSS_CPC?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: xc.cpct

# 第四数据源
  datasourcefourth:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.168.117:3306/fpc_system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: Yanlei2018

#redis相关配置
  redis:
    host: 134.96.252.170
    port: 30305
    password: xc.cpct
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
  #ES
  elasticsearch:
      ip: 134.108.3.30
      port: 9300
      pool: 5
      cluster:
        name: es-cpct
#是否同步
sync:
  value: 0



