#端口配置
server:
  port: 8080

#数据库相关配置  cpc库
spring:
# 第一数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.253.29:8801/smt_bss_cpc_cpct?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_cpct_user
    password: cpc_cpct_user_123

# 第二数据源
  datasourceprd:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.253.29:8801/smt_bss_cpc_cpct?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_cpct_user
    password: cpc_cpct_user_123
# 第四数据源
  datasourcefourth:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.253.29:8801/smt_bss_cpc_evo2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_user
    password: cpc_user_123



#redis相关配置
  redis:
    host: 134.96.252.170
    port: 30305
    password: xc.cpct
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000

#集团定制的redis配置prod环境
redisConfig:
   ip: 134.108.0.57
   port: 41601
   database: 4970
   password: bss_cpcp_poczsc_user#Bsscpc!z3