package com.zjtelcom.cpct_offer.dao.inst;

import com.zjtelcom.cpct.domain.channel.RequestInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;


public interface RequestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long requestTemplateInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_info
     *
     * @mbg.generated
     */
    int insert(RequestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_info
     *
     * @mbg.generated
     */
    RequestInfo selectByPrimaryKey(Long requestTemplateInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_info
     *
     * @mbg.generated
     */
    List<RequestInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestInfo record);
}