#端口配置
server:
  port: 8080

spring:
# 第一数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_user_cpct
    password: cpc_user_cpct_prod

# 第二数据源  需求函相关
  datasourceprd:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc_evo?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_user_cpct
    password: cpc_user_cpct_prod

#redis相关配置
  redis:
    host: 134.96.252.170
    port: 30305
    password: xc.cpct
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000
  #ES
  elasticsearch:
      ip: 134.108.3.30
      port: 9300
      pool: 5
      cluster:
        name: es-cpct


redisConfig:
   ip: 134.108.0.59
   port: 41701
   database: 4970
   password: bss_cpcp_pocpro_user#bssCpc_ro


redisConfig_Prd:
   ip: 134.108.0.59
   port: 41701
   database: 4970
   password: bss_cpcp_pocpro_user#bssCpc_ro

