#端口配置
server:
  port: 8080

spring:
# 第一数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.231.202:8801/smt_bss_cpc1213?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_user
    password: cpc_user_123

# 第二数据源  需求函相关
  datasourceprd:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.96.231.202:8801/smt_bss_cpc_evo2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpc_user_cpct
    password: cpc_user_cpct_msit


#redis相关配置
  redis:
    host: 134.96.252.170
    port: 30305
    password: xc.cpct
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000





