#端口配置
server:
  port: 30809

#数据库相关配置
#spring:
#  datasource:
#    url: jdbc:mysql://47.94.168.117:3306/fpc_system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#    username: root
#    password: Yanlei2018
#    driver-class-name: com.mysql.jdbc.Driver

#数据库相关配置
spring:
# 第一数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy



  redis:
      host: 47.94.168.117
      port: 6379
      password: 9bOCHtdJkNZ1hb2e35OmgIrLvGEaBXuT2udRBQNt5VQ
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 30000


#调用统一平台的参数 生产环境
platformConfig:
   channel: CLZX
   channel_token: rAx5T2pIvvw5W9vQ
   bis_module: 内容策略中心
   bis_detail: 内容策略中心
   version: v1.0

#集团定制的redis配置prod环境
redisConfig:
   ip: 134.108.0.59
   port: 41701
   database: 4970
   password: bss_cpcp_pocpro_user#bssCpc_ro

#集团定制的redis配置生产环境
redisConfig_Prd:
   ip: 134.108.0.59
   port: 41701
   database: 4970
   password: bss_cpcp_pocpro_user#bssCpc_ro