apiVersion: v1
kind: Service
metadata:
  name: bss-cpct-dubbo-label
  labels:
    name: bss-cpct-dubbo-label
spec:
  type: NodePort
  ports:
  - port: 30804
    nodePort: 30804
  selector:
    name: bss-cpct-dubbo-label
