#端口配置
server:
  port: 8080

#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy
    driver-class-name: com.mysql.jdbc.Driver

# 第二数据源   独立schema
  datasource_prd:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc_zsc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy

# 第三数据源   链接cpc数据库
  datasourcethird:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy

# 第四数据源
  datasourcefourth:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc_evo?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy

#redis相关配置
  redis:
    host: 134.96.252.170
    port: 30305
    password: xc.cpct
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000


#集团CPCT定制的redis配置prod环境
redisConfig:
   ip: 134.108.0.40,134.108.0.41
   port: 9051
   database: 0
   password: CRM_CPCP_002_USER#bssCpc_ro


redisConfig_Prd:
   ip: 134.108.0.59
   port: 41701
   database: 4970
   password: bss_cpcp_pocpro_user#bssCpc_ro


ctg:
  namesrvAddr: 134.108.11.159:9892;134.108.11.160:9892;134.108.11.161:9892
  cpctGroupName: cpct_file_import
  namesrvAuthID: cpct_user
  namesrvAuthPwd: cpct_user123
  consumeOrderly: false
  instanceName: prod_cpct
  maxMessageSize: 8242880
  sendMaxRetryTimes: 2
  sendMsgTimeout: 30000
  compressMsgBodyOverHowmuch: 4098
  clusterName: pst_crm_mq
  tenantID: 2
  cpctTopic: cpct_topic_import
  clientWorkerThreads: 4

  # 服务包队列
  cpctSerpackageTopic: cpct_es_servicepackage_prod
  cpctSerpackageGroup: cpct_es_servicepackage_group_prod
