apiVersion: v1
kind: Service
metadata:
  name: crm-cpct-dubbo-eventapi
  labels:
    name: crm-cpct-dubbo-eventapi
spec:
  type: NodePort
  ports:
  - port: 30816
    nodePort: 30816
  selector:
    name: crm-cpct-dubbo-eventapi
