apiVersion: v1
kind: Service
metadata:
  name: bss-cpct-dubbo-ser
  labels:
    name: bss-cpct-dubbo-ser
spec:
  type: NodePort
  ports:
  - port: 30808
    nodePort: 30808
  selector:
    name: bss-cpct-dubbo-ser
