#端口配置
server:
  port: 30810

#数据库相关配置  cpc库
spring:
# 第一数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy

# 第二数据源
  datasource_prd:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc_zsc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy

# 第三数据源   链接cpc准生产数据库
  datasourcethird:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy

# 第四数据源
  datasourcefourth:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.108.1.12:8803/smt_bss_cpc_evo?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: cpct_prod
    password: DWdtV7Wy



#redis相关配置
  redis:
    host: 134.96.252.170
    port: 30305
    password: xc.cpct
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 30000

#集团CPCT定制的redis配置prod环境
redisConfig:
   ip: 134.108.0.40,134.108.0.41
   port: 9051
   database: 0
   password: CRM_CPCP_002_USER#bssCpc_ro


redisConfig_Prd:
   ip: 134.108.0.59,134.108.0.60
   port: 41701
   database: 4970
   password: bss_cpcp_pocpro_user#bssCpc_ro


ctg:
  namesrvAddr: 134.108.6.201:9876;134.108.6.202:9876;134.108.6.203:9876
  cpctGroupName: cpct_detailed_list_group
  namesrvAuthID: cpct_user
  namesrvAuthPwd: Cpct!@3e#
  consumeOrderly: false
  instanceName: prod_cpct
  maxMessageSize: 8242880
  sendMaxRetryTimes: 2
  sendMsgTimeout: 30000
  compressMsgBodyOverHowmuch: 4098
  clusterName: CRM_MQ
  tenantID: 2
  cpctTopic: cpct_detailed_list_topic
  clientWorkerThreads: 4


  # 第四topic es日志添加队列中转
  cpctEsLogTopic: cpct_eslog_prod
  cpctEsLogGroup: cpct_eslog_group_prod

elasticsearch:
  ip: 134.108.6.161
  port: 9300
  pool: 5
  cluster.name: my-application1