apiVersion: v1
kind: Service
metadata:
  name: bss-cpct-count
  labels:
    name: bss-cpct-count
spec:
  type: NodePort
  ports:
  - port: 30814
    nodePort: 30814
  selector:
    name: bss-cpct-count
